# Generated by Django 5.0.3 on 2024-09-12 14:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('email', models.EmailField(max_length=255, verbose_name='e-mail')),
                ('subject', models.CharField(max_length=240, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
            ],
            options={
                'verbose_name': 'contact form submission',
                'verbose_name_plural': 'contact form submissions',
            },
        ),
        migrations.CreateModel(
            name='HtmxContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('display_join_us_block', models.BooleanField(default=True, help_text='Show the join us block at the botton of this page. To modify its content, go to Settings - Website customization.', verbose_name='Display join us block')),
                ('name_label', models.CharField(default='Your name', help_text='Label for the Name field.', max_length=250, verbose_name='name')),
                ('email_label', models.CharField(default='Your e-mail', help_text='Label for the e-mail field.', max_length=250, verbose_name='email')),
                ('subject_label', models.CharField(default='Subject', help_text='Label for the Subject field.', max_length=250, verbose_name='subject')),
                ('message_label', models.CharField(default='Message', help_text='Label for the Message field.', max_length=250, verbose_name='message')),
                ('success_msg', wagtail.fields.RichTextField(default='Message sent, thanks for contacting us!', verbose_name='success message')),
                ('to_address', models.EmailField(blank=True, help_text='E-mail to notify when a new submission is received. Leave it empty to disable the notifications.', max_length=254, null=True, verbose_name='to address')),
                ('notification_subject', models.CharField(blank=True, help_text='If empty, you will not get e-mail notifications for new form submissions.', max_length=250, null=True, verbose_name='subject')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
