# Generated by Django 5.1.3 on 2024-11-28 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_htmx_contact_form", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="htmxcontactpage",
            name="phone_label",
        ),
    ]
