# Generated by Django 5.0.3 on 2024-09-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_htmx_contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmxcontactpage',
            name='phone_label',
            field=models.CharField(default='Phone', help_text='Label for the Phone field.', max_length=250, verbose_name='subject'),
        ),
    ]
