# Generated by Django 5.0.3 on 2024-09-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_htmx_contact_form', '0002_htmxcontactpage_phone_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='personal_data_auth',
            field=models.BooleanField(default=True, verbose_name='Treatment of personal data authorization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='htmxcontactpage',
            name='personal_data_auth_label',
            field=models.CharField(default='I authorize my personal data treatment', help_text='Label for the Personal data authorization field.', max_length=250, verbose_name='personal data authorization'),
        ),
        migrations.AddField(
            model_name='htmxcontactpage',
            name='personal_data_auth_text',
            field=models.TextField(blank=True, default='', help_text='Legal text displayed alongside the personal data authorization checkbox.', verbose_name='personal data authorization legal text'),
        ),
    ]
