# Generated by Django 5.0.3 on 2024-09-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_htmx_contact_form', '0003_contactsubmission_personal_data_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmxcontactpage',
            name='notification_subject',
            field=models.CharField(blank=True, default='', help_text='If empty, you will not get e-mail notifications for new form submissions.', max_length=250, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='htmxcontactpage',
            name='success_msg',
            field=models.CharField(default='Message sent, thanks for contacting us!', max_length=250, verbose_name='success message'),
        ),
        migrations.AlterField(
            model_name='htmxcontactpage',
            name='to_address',
            field=models.EmailField(blank=True, default='', help_text='E-mail to notify when a new submission is received. Leave it empty to disable the notifications.', max_length=254, verbose_name='to address'),
        ),
    ]
