# Generated by Django 5.0.3 on 2024-09-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_htmx_contact_form', '0004_alter_htmxcontactpage_notification_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmxcontactpage',
            name='menu_label',
            field=models.CharField(blank=True, help_text='If not set, the menu title will be the page title.', max_length=15, null=True, verbose_name='Menu title'),
        ),
    ]
