# Generated by Django 5.1.3 on 2024-11-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_htmx_contact_form', '0005_htmxcontactpage_menu_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmxcontactpage',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
