# Generated by Django 5.1.3 on 2024-11-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_htmx_contact_form', '0005_htmxcontactpage_menu_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmxcontactpage',
            name='menu_label',
            field=models.CharField(blank=True, default='', help_text='If not set, the menu title will be the page title.', max_length=15, verbose_name='Menu title'),
            preserve_default=False,
        ),
    ]
