# Generated by Django 5.0.3 on 2024-09-19 10:17

import django.db.models.deletion
import project.fields.flowbite
import project.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', project.fields.flowbite.ModelCharField(max_length=50, verbose_name='name')),
                ('surnames', project.fields.flowbite.ModelCharField(max_length=50, verbose_name='surname')),
                ('email', project.fields.flowbite.ModelEmailField(max_length=255, unique=True, verbose_name='email address')),
                ('email_verification_code', models.CharField(default='0000')),
                ('email_verified', models.BooleanField(default=False)),
                ('phone', project.fields.flowbite.ModelCharField(blank=True, max_length=20, null=True, verbose_name='Contact telephone')),
                ('address', project.fields.flowbite.ModelCharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('dni', project.fields.flowbite.ModelCharField(blank=True, max_length=10, null=True, verbose_name='National Identity Document')),
                ('bank_account', project.fields.flowbite.ModelCharField(blank=True, max_length=24, null=True, verbose_name='Bank account')),
                ('charge', project.fields.flowbite.ModelCharField(blank=True, max_length=50, null=True, verbose_name='Charge')),
                ('governing_council_member', project.fields.flowbite.ModelBooleanField(blank=True, default=False, help_text='Is this user a governing council member?', null=True, verbose_name='Is governing council member')),
                ('partner_id', project.fields.flowbite.ModelCharField(blank=True, max_length=50, null=True, verbose_name='Partner ID')),
                ('entry_year', project.fields.flowbite.ModelCharField(blank=True, max_length=4, null=True, verbose_name='Entry year')),
                ('corporate_contribution', project.fields.flowbite.ModelCharField(blank=True, max_length=10, null=True, verbose_name='Corporate contribution')),
                ('voluntary_contribution', project.fields.flowbite.ModelCharField(blank=True, max_length=10, null=True, verbose_name='Voluntary contribution')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is staff')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('projects', models.ManyToManyField(blank=True, related_name='user_projects', to='main.project', verbose_name='Projects')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
