# Generated by Django 5.1.3 on 2025-05-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_data_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driving_group_member',
            field=models.BooleanField(default=False, verbose_name='Is driving group member'),
        ),
        migrations.AlterField(
            model_name='user',
            name='governing_council_member',
            field=models.BooleanField(default=False, verbose_name='Is governing council member'),
        ),
    ]
