# Generated by Django 5.0.3 on 2024-10-04 08:42

import django.db.models.deletion
import project.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_data_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='Bank account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='corporate_contribution',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Corporate contribution'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='National Identity Document'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='entry_year',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Entry year'),
        ),
        migrations.AlterField(
            model_name='user',
            name='governing_council_member',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is governing council member'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Partner ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Contact telephone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surnames',
            field=models.CharField(default='', max_length=50, verbose_name='surname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='voluntary_contribution',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Voluntary contribution'),
        ),
        migrations.CreateModel(
            name='UserCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50, verbose_name='Charge name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'abstract': False,
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='user',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_charge', to='users.usercharge'),
        ),
    ]
