# Generated by Django 5.0.3 on 2024-10-03 13:33

import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_data_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=project.fields.flowbite.ModelCharField(blank=True, default='', max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_account',
            field=project.fields.flowbite.ModelCharField(blank=True, default='', max_length=24, verbose_name='Bank account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='corporate_contribution',
            field=project.fields.flowbite.ModelCharField(blank=True, default='', max_length=10, verbose_name='Corporate contribution'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=project.fields.flowbite.ModelCharField(default='', max_length=10, unique=True, verbose_name='National Identity Document'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=project.fields.flowbite.ModelEmailField(blank=True, help_text='If this field is empty a default email will be added.', max_length=255, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='entry_year',
            field=project.fields.flowbite.ModelCharField(blank=True, default='', max_length=4, verbose_name='Entry year'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=project.fields.flowbite.ModelCharField(default='', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_id',
            field=project.fields.flowbite.ModelCharField(blank=True, default='', max_length=50, verbose_name='Partner ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=project.fields.flowbite.ModelCharField(blank=True, default='', max_length=20, verbose_name='Contact telephone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surnames',
            field=project.fields.flowbite.ModelCharField(default='', max_length=50, verbose_name='surname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='voluntary_contribution',
            field=project.fields.flowbite.ModelCharField(blank=True, default='', max_length=10, verbose_name='Voluntary contribution'),
        ),
    ]
