# Generated by Django 5.0.3 on 2024-10-03 14:11

import django.db.models.deletion
import project.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_email_verification_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50, verbose_name='Charge name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'abstract': False,
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='user',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_charge', to='users.usercharge'),
        ),
    ]
