# Generated by Django 5.0.3 on 2024-04-09 13:43

import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_verification_code_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=project.fields.flowbite.ModelEmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=project.fields.flowbite.ModelCharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surnames',
            field=project.fields.flowbite.ModelCharField(blank=True, default='', max_length=50, verbose_name='surname'),
        ),
    ]
