# Generated by Django 5.0.3 on 2024-05-10 10:02

import django.db.models.deletion
import project.fields.flowbite
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email_alter_user_name_alter_user_surnames'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'usuari', 'verbose_name_plural': 'usuaris'},
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='creat per'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=project.fields.flowbite.ModelEmailField(max_length=255, unique=True, verbose_name='correu electrònic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=project.fields.flowbite.ModelCharField(max_length=50, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surnames',
            field=project.fields.flowbite.ModelCharField(blank=True, default='', max_length=50, verbose_name='cognoms'),
        ),
    ]
