# Generated by Django 5.0.3 on 2024-05-10 14:35

import django.db.models.deletion
import project.fields.flowbite
import project.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', project.fields.flowbite.ModelEmailField(help_text="Correu electrònic per subscriure't on rebràs el nostre butlletí", max_length=100, unique=True, verbose_name='correu electronic')),
                ('name', project.fields.flowbite.ModelCharField(help_text='El teu nom', max_length=50, verbose_name='nom')),
                ('surnames', project.fields.flowbite.ModelCharField(help_text='Els teus cognoms', max_length=100, verbose_name='cognoms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'newsletter',
                'verbose_name_plural': 'newsletters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', project.fields.flowbite.ModelCharField(help_text='Nom del projecte', max_length=50, unique=True, verbose_name='nom')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'projecte',
                'verbose_name_plural': 'projectes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', project.fields.flowbite.ModelCharField(help_text='Títol del document', max_length=50, verbose_name='Títol')),
                ('file', models.FileField(help_text='Fitxer', storage=project.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='file name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.project')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
