# Generated by Django 5.0.3 on 2024-05-30 15:48

import django.db.models.deletion
import project.fields.flowbite
import project.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', project.fields.flowbite.ModelEmailField(help_text='Email where you will receive our newsletter', max_length=100, unique=True)),
                ('name', project.fields.flowbite.ModelCharField(help_text='Your name', max_length=50)),
                ('surnames', project.fields.flowbite.ModelCharField(help_text='Your surnames', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'newsletter subscriber',
                'verbose_name_plural': 'newsletter subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', project.fields.flowbite.ModelCharField(help_text='Project name', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', project.fields.flowbite.ModelCharField(help_text='Project', max_length=50)),
                ('file', models.FileField(help_text='File', storage=project.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='file name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.project')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
