# Generated by Django 5.0.3 on 2024-05-10 10:45

import project.fields.flowbite
import project.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'projecte', 'verbose_name_plural': 'projectes'},
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Fitxer', storage=project.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='file name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=project.fields.flowbite.ModelCharField(help_text='Títol del document', max_length=50, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=project.fields.flowbite.ModelEmailField(help_text="Correu electrònic per subscriure't on rebràs el nostre butlletí", max_length=100, unique=True, verbose_name='correu electronic'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=project.fields.flowbite.ModelCharField(help_text='El teu nom', max_length=50, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='surnames',
            field=project.fields.flowbite.ModelCharField(help_text='Els teus cognoms', max_length=100, verbose_name='cognoms'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=project.fields.flowbite.ModelCharField(help_text='Nom del projecte', max_length=50, unique=True, verbose_name='nom'),
        ),
    ]
