# Generated by Django 5.0.3 on 2024-04-30 14:10

import project.fields.flowbite
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', project.fields.flowbite.ModelEmailField(help_text='Email to subscribe where you will receive our newsletter', max_length=100, unique=True)),
                ('name', project.fields.flowbite.ModelCharField(help_text='Your name', max_length=50)),
                ('surnames', project.fields.flowbite.ModelCharField(help_text='Your surnames)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'newsletter',
                'verbose_name_plural': 'newsletters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
