# Generated by Django 5.0.3 on 2024-10-08 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='annual_energy',
            field=models.CharField(blank=True, default='', help_text='Project annual energy (kWh/year)', verbose_name='Annual energy'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='energy_power',
            field=models.CharField(blank=True, default='', help_text='Project energy power (kW)', verbose_name='Energy power'),
        ),
        migrations.AlterField(
            model_name='project',
            name='investment',
            field=models.CharField(blank=True, default='', help_text='Project investment (€)', verbose_name='Investment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(blank=True, default=False, help_text='Is this project public?', verbose_name='Is public'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='project', to='main.projecttype', verbose_name='Project type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PS', 'Project in study phase'), ('AP', 'Active Project'), ('OP', 'Future projects or other projects')], default='', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='project type name'),
        ),
    ]
