# Generated by Django 5.0.3 on 2024-10-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='access_permission_role',
            field=models.CharField(choices=[('GC', 'Governing Council and Driving Group'), ('AU', 'All users')], default='AU', max_length=2, verbose_name='Access Permission Role'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Description'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='documents', to='main.project', verbose_name='Project'),
        ),
    ]
