# Generated by Django 5.0.3 on 2024-08-07 10:27

from django.db import migrations


def generate_project_types(apps, schema_editor):
    project_model = apps.get_model("main", "ProjectType")
    project_type_list = [
        "Photovoltaic self-consumption",
        "Electric mobility",
        "Hydroelectric",
        "Biomassa",
        "Energy efficiency",
        "Water Saving",
        "Sustainable food",
    ]


    for p_type in project_type_list:
        project_type = project_model()
        project_type.name = p_type
        project_type.save()
        print(f"\n\tInitial project type {p_type} created.")


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [migrations.RunPython(generate_project_types)]
