# Generated by Django 5.0.3 on 2024-04-09 13:38

import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='field_number',
            field=project.fields.flowbite.ModelIntegerField(blank=True, help_text='Help field_number', null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_password',
            field=project.fields.flowbite.ModelPasswordField(help_text='Help field_password', max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_password_confirm',
            field=project.fields.flowbite.ModelPasswordField(help_text='Help field_password_confirm', max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_radio',
            field=project.fields.flowbite.ModelRadioField(choices=[('OP1', 'Option 1'), ('OP2', 'Option 2'), ('OP3', 'Option 3')], help_text='Help field_radio', max_length=4),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_select_checkbox',
            field=project.fields.flowbite.ModelSelectCheckboxField(blank=True, choices=[('OP1', 'Option 1'), ('OP2', 'Option 2'), ('OP3', 'Option 3')], default='OP1', help_text='Help field_select_checkbox', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_select_dropdown',
            field=project.fields.flowbite.ModelSelectDropdownField(choices=[('OP1', 'Option 1'), ('OP2', 'Option 2'), ('OP3', 'Option 3')], default='OP1', help_text='Help field_select_dropdown', max_length=4),
        ),
    ]
