# Generated by Django 5.0.3 on 2024-04-22 15:17

import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_data_field_number_alter_data_field_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='field_select_checkbox',
            field=project.fields.flowbite.ModelSelectCheckboxField(blank=True, default='OP1', help_text='Help field_select_checkbox', max_length=250, null=True),
        ),
    ]
