# Generated by Django 5.1.3 on 2024-11-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_document_responsible_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(blank=True, default=False, help_text='If checked, this project will be published to the website.', verbose_name='Is public'),
        ),
    ]
