# Generated by Django 5.1.3 on 2025-05-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_documentcomission_document_area_alter_document_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='area',
            field=models.CharField(blank=True, choices=[('TP', 'Technical projects'), ('CP', "Cooperative's project"), ('CR', 'Consell rector'), ('C', 'Comissions')], default='', verbose_name='Area'),
            preserve_default=False,
        ),
    ]
