# Generated by Django 5.1.3 on 2024-11-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_remove_project_is_public_project_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
    ]
