# Generated by Django 5.0.3 on 2024-09-04 13:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed', models.TextField(blank=True, default='', verbose_name='Embed code')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('overlay_title', models.CharField(blank=True, default='', max_length=80, verbose_name='Title')),
                ('overlay_body', models.TextField(blank=True, default='', verbose_name='Text')),
                ('overlay_button_text', models.CharField(blank=True, default='', max_length=20, verbose_name='Button title')),
                ('display_header_highlight', models.BooleanField(default=True, help_text='Per mostrar el missatge superposat a la capçalera cal marcar aquesta opció i omplir les dades del bloc Header overlay message.', verbose_name='Display header highlighted overlay')),
                ('description', wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description')),
                ('header_image', models.ForeignKey(help_text="Aquesta imatge està pensada per ser decorativa i crear acompanyar el contingut. Segons la resolució i el dispositiu de l'usuari, la mida i proporció variarà, i per tant es retallaran parts de la imatge. La proporció recomanada és de 2x1, amb una mida mínima de 2.000x1.000px.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Header image')),
                ('overlay_button_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Linked page')),
                ('overlay_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SocialMediaIconsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, default='', help_text='Facebook URL', null=True)),
                ('youtube', models.URLField(blank=True, default='', help_text='Youtube URL', null=True)),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/castelletsostenible/', help_text='Instagram URL', null=True)),
                ('x', models.URLField(blank=True, default='', help_text='X URL', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StringsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Contact e-mail')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Phone')),
                ('footer_name', models.CharField(blank=True, default='© Nom entitat SCCL, 2024', help_text='Legal name and year', max_length=60, verbose_name='Footer name')),
                ('title_prefix', models.CharField(default='Castellet Sostenible', help_text="This will be prefixed to every page title. the title is shown in the browser's tab.", max_length=60, verbose_name='Title prefix')),
                ('authorship', models.CharField(blank=True, default='Desenvolupat per Codi Cooperatiu · Dissenyat per Utopig Studio', max_length=150, verbose_name='Authorship')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Website strings',
            },
        ),
    ]
