# Generated by Django 5.0.3 on 2024-09-10 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_button_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Header button linked page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_button_text',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Header button title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_description',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Header description'),
        ),
    ]
