# Generated by Django 5.0.3 on 2024-09-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='header_image',
        ),
    ]
