# Generated by Django 5.0.3 on 2024-09-04 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringssettings',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Logo'),
        ),
    ]
