# Generated by Django 5.0.3 on 2024-09-04 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('web', '0002_remove_homepage_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_image',
            field=models.ForeignKey(help_text="Aquesta imatge està pensada per ser decorativa i crear acompanyar el contingut. Segons la resolució i el dispositiu de l'usuari, la mida i proporció variarà, i per tant es retallaran parts de la imatge. La proporció recomanada és de 2x1, amb una mida mínima de 2.000x1.000px.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_body',
            field=models.TextField(blank=True, default='', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_button_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Linked page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_button_text',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Button title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_title',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Title'),
        ),
    ]
