# Generated by Django 5.0.3 on 2024-09-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_homepage_header_button_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='description',
            new_name='video_description',
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_title',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_youtube_url',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='YouTube URL'),
        ),
    ]
