# Generated by Django 5.0.3 on 2024-09-10 12:03

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_description_homepage_video_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='documents',
            field=wagtail.fields.StreamField([('document', 0)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='documents_description',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='documents_title',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Title'),
        ),
    ]
