# Generated by Django 5.0.3 on 2024-09-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_homepage_header_image_homepage_overlay_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='display_header_highlight',
            field=models.BooleanField(default=True, help_text='Per mostrar el missatge superposat a la capçalera cal marcar aquesta opció i omplir les dades del bloc Header overlay message.', verbose_name='Display header highlighted overlay'),
        ),
    ]
