# Generated by Django 5.0.3 on 2024-09-10 14:01

import apps.web.models.home
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_homepage_documents_homepage_documents_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='documents',
            field=wagtail.fields.StreamField([('document', 2)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': apps.web.models.home.DocumentBlock.DocumentIconChoices}), 2: ('wagtail.blocks.StructBlock', [[('file', 0), ('icon', 1)]], {})}, null=True),
        ),
    ]
