# Generated by Django 5.0.3 on 2024-09-04 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('web', '0004_homepage_display_header_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', help_text='Contact e-mail', max_length=254, null=True)),
                ('address', models.TextField(blank=True, default='', help_text='Address', null=True)),
                ('phone', models.CharField(blank=True, default='', help_text='Phone number', max_length=30, null=True)),
                ('footer_name', models.CharField(blank=True, default='© Nom entitat SCCP, 2024', help_text='Footer legal name and year', max_length=60, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
