# Generated by Django 5.0.3 on 2024-09-12 10:08

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_homepage_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationsettings',
            name='join_us_text',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='customizationsettings',
            name='join_us_title',
            field=models.CharField(default='Join Castellet Sostenible', max_length=240, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='display_join_us_block',
            field=models.BooleanField(default=False, help_text='Show the join us block at the botton of this page. To modify its content, go to Settings - Website customization.', verbose_name='Display join us block'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='documents',
            field=wagtail.fields.StreamField([('document', 4)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('doc-full-inverse', 'General document'), ('image', 'Image file'), ('desktop', 'Video file'), ('comment', 'Audio file')]}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('file', 0), ('icon', 1), ('title', 2), ('description', 3)]], {})}, null=True),
        ),
    ]
