# Generated by Django 5.0.3 on 2024-09-04 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('web', '0005_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Strings',
        ),
        migrations.AlterModelOptions(
            name='strings',
            options={'verbose_name': 'Website strings'},
        ),
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed', models.TextField(blank=True, default='', verbose_name='Embed code')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
