# Generated by Django 5.0.3 on 2024-09-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_customizationsettings_join_us_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizationsettings',
            name='join_us_title',
            field=models.CharField(default='Uneix-te a Castellet Sostenible', max_length=240, verbose_name='Títol'),
        ),
    ]
