# Generated by Django 5.0.3 on 2024-09-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_settings_strings_alter_strings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strings',
            name='title_prefix',
            field=models.CharField(blank=True, default='Castellet Sostenible', help_text="This will be prefixed to every page title. the title is shown in the browser's tab.", max_length=60, null=True, verbose_name='hola'),
        ),
        migrations.AlterField(
            model_name='strings',
            name='footer_name',
            field=models.CharField(blank=True, default='© Nom entitat SCCL, 2024', help_text='Footer legal name and year', max_length=60, null=True),
        ),
    ]
