# Generated by Django 5.0.3 on 2024-09-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_strings_title_prefix_alter_strings_footer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='strings',
            name='authorship',
            field=models.CharField(blank=True, default='Desenvolupat per Codi Cooperatiu · Dissenyat per Utopig Studio', max_length=150, verbose_name='Authorship'),
        ),
        migrations.AlterField(
            model_name='strings',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='strings',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Contact e-mail'),
        ),
        migrations.AlterField(
            model_name='strings',
            name='footer_name',
            field=models.CharField(blank=True, default='© Nom entitat SCCL, 2024', help_text='Legal name and year', max_length=60, verbose_name='Footer name'),
        ),
        migrations.AlterField(
            model_name='strings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='strings',
            name='title_prefix',
            field=models.CharField(default='Castellet Sostenible', help_text="This will be prefixed to every page title. the title is shown in the browser's tab.", max_length=60, verbose_name='Title prefix'),
        ),
    ]
