# Generated by Django 5.0.3 on 2024-09-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_customizationsettings_join_us_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='display_join_us_block',
            field=models.BooleanField(default=True, help_text='Show the join us block at the botton of this page. To modify its content, go to Settings - Website customization.', verbose_name='Display join us block'),
        ),
    ]
