# Generated by Django 5.0.3 on 2024-09-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('web', '0008_strings_authorship_alter_strings_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Strings',
            new_name='StringsSettings',
        ),
        migrations.CreateModel(
            name='SocialMediaIconsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, default='https://www.facebook.com/moblesciurans', help_text='Facebook URL', null=True)),
                ('youtube', models.URLField(blank=True, default='http://www.youtube.com/user/ciuransmobles', help_text='Youtube URL', null=True)),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/ciuransmobles', help_text='Instagram URL', null=True)),
                ('vimeo', models.URLField(blank=True, default='https://vimeo.com/moblesciurans', help_text='Vimeo URL', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
