# Generated by Django 5.0.3 on 2024-09-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_rename_strings_stringssettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaiconssettings',
            name='vimeo',
        ),
        migrations.AddField(
            model_name='socialmediaiconssettings',
            name='x',
            field=models.URLField(blank=True, default='', help_text='X URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaiconssettings',
            name='facebook',
            field=models.URLField(blank=True, default='', help_text='Facebook URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaiconssettings',
            name='instagram',
            field=models.URLField(blank=True, default='https://www.instagram.com/castelletsostenible/', help_text='Instagram URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaiconssettings',
            name='youtube',
            field=models.URLField(blank=True, default='', help_text='Youtube URL', null=True),
        ),
    ]
