# Generated by Django 5.0.3 on 2024-09-12 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('web', '0009_aboutuspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('display_join_us_block', models.BooleanField(default=True, help_text='Show the join us block at the botton of this page. To modify its content, go to Settings - Website customization.', verbose_name='Display join us block')),
                ('header_description', models.CharField(blank=True, default='', max_length=250, verbose_name='Header description')),
                ('header_button_text', models.CharField(blank=True, default='', max_length=20, verbose_name='Header button title')),
                ('overlay_title', models.CharField(blank=True, default='', max_length=80, verbose_name='Title')),
                ('overlay_body', models.TextField(blank=True, default='', verbose_name='Text')),
                ('overlay_button_text', models.CharField(blank=True, default='', max_length=20, verbose_name='Button title')),
                ('display_header_highlight', models.BooleanField(default=True, help_text='Per mostrar el missatge superposat a la capçalera cal marcar aquesta opció i omplir les dades del bloc Header overlay message.', verbose_name='Display header highlighted overlay')),
                ('header_button_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Header button linked page')),
                ('header_image', models.ForeignKey(help_text="Aquesta imatge està pensada per ser decorativa i crear acompanyar el contingut. Segons la resolució i el dispositiu de l'usuari, la mida i proporció variarà, i per tant es retallaran parts de la imatge. La proporció recomanada és de 2x1, amb una mida mínima de 2.000x1.000px.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Header image')),
                ('overlay_button_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Linked page')),
                ('overlay_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('display_join_us_block', models.BooleanField(default=True, help_text='Show the join us block at the botton of this page. To modify its content, go to Settings - Website customization.', verbose_name='Display join us block')),
                ('header_description', models.CharField(blank=True, default='', max_length=250, verbose_name='Header description')),
                ('header_button_text', models.CharField(blank=True, default='', max_length=20, verbose_name='Header button title')),
                ('overlay_title', models.CharField(blank=True, default='', max_length=80, verbose_name='Title')),
                ('overlay_body', models.TextField(blank=True, default='', verbose_name='Text')),
                ('overlay_button_text', models.CharField(blank=True, default='', max_length=20, verbose_name='Button title')),
                ('display_header_highlight', models.BooleanField(default=True, help_text='Per mostrar el missatge superposat a la capçalera cal marcar aquesta opció i omplir les dades del bloc Header overlay message.', verbose_name='Display header highlighted overlay')),
                ('header_button_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Header button linked page')),
                ('header_image', models.ForeignKey(help_text="Aquesta imatge està pensada per ser decorativa i crear acompanyar el contingut. Segons la resolució i el dispositiu de l'usuari, la mida i proporció variarà, i per tant es retallaran parts de la imatge. La proporció recomanada és de 2x1, amb una mida mínima de 2.000x1.000px.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Header image')),
                ('overlay_button_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Linked page')),
                ('overlay_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
