# Generated by Django 5.0.3 on 2024-09-13 14:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('web', '0010_projectdetailpage_projectlistpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('display_join_us_block', models.BooleanField(default=True, help_text='Show the join us block at the botton of this page. To modify its content, go to Settings - Website customization.', verbose_name='Display join us block')),
                ('questions', wagtail.fields.StreamField([('question', 1)], block_lookup={0: ('wagtail.blocks.TextBlock', (), {'required': True}), 1: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 0)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
