# Generated by Django 5.0.3 on 2024-09-13 15:19

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_faqpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='menu_label',
            field=models.CharField(blank=True, help_text='If not set, the menu title will be the page title.', max_length=15, null=True, verbose_name='Menu title'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='menu_label',
            field=models.CharField(blank=True, help_text='If not set, the menu title will be the page title.', max_length=15, null=True, verbose_name='Menu title'),
        ),
        migrations.AddField(
            model_name='projectlistpage',
            name='menu_label',
            field=models.CharField(blank=True, help_text='If not set, the menu title will be the page title.', max_length=15, null=True, verbose_name='Menu title'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='questions',
            field=wagtail.fields.StreamField([('question', 2)], block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Question', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Answer', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}, verbose_name='Questions & Answers'),
        ),
    ]
