# Generated by Django 5.0.3 on 2024-09-18 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('web', '0014_newsdetailpage_newslistpage_newstag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdetailpage',
            name='header_image',
            field=models.ForeignKey(help_text="Aquesta imatge està pensada per ser decorativa i crear acompanyar el contingut. Segons la resolució i el dispositiu de l'usuari, la mida i proporció variarà, i per tant es retallaran parts de la imatge. La proporció recomanada és de 2x1, amb una mida mínima de 2.000x1.000px.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
    ]
