# Generated by Django 5.1.3 on 2024-11-12 11:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_newsdetailpage_header_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaggedBlog',
            new_name='TaggedNews',
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='questions',
            field=wagtail.fields.StreamField([('question', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Question', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Answer', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}, verbose_name='Questions & Answers'),
        ),
    ]
