# Generated by Django 5.1.3 on 2024-11-12 15:48

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_rename_taggedblog_taggednews_alter_faqpage_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlistpage',
            name='projects_active_description',
            field=wagtail.fields.RichTextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='projectlistpage',
            name='projects_active_title',
            field=models.CharField(default='Projects we are currently working on', max_length=200, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='projectlistpage',
            name='projects_other_description',
            field=wagtail.fields.RichTextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='projectlistpage',
            name='projects_other_title',
            field=models.CharField(default='Future and other projects', max_length=200, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='projectlistpage',
            name='projects_working_on_description',
            field=wagtail.fields.RichTextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='projectlistpage',
            name='projects_working_on_title',
            field=models.CharField(default='Projects being studied', max_length=200, verbose_name='Title'),
        ),
    ]
