# Generated by Django 5.1.3 on 2024-11-12 15:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_projectlistpage_projects_active_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectlistpage',
            old_name='projects_working_on_title',
            new_name='projects_study_phase_title',
        ),
        migrations.RemoveField(
            model_name='projectlistpage',
            name='projects_working_on_description',
        ),
        migrations.AddField(
            model_name='projectlistpage',
            name='projects_study_phase_description',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projectlistpage',
            name='projects_active_description',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projectlistpage',
            name='projects_other_description',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
