# Generated by Django 5.1.3 on 2024-11-14 10:49

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_alter_project_created_at'),
        ('wagtailimages', '0027_image_description'),
        ('web', '0018_rename_projects_working_on_title_projectlistpage_projects_study_phase_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetailpage',
            name='display_header_highlight',
        ),
        migrations.RemoveField(
            model_name='projectdetailpage',
            name='header_button_page',
        ),
        migrations.RemoveField(
            model_name='projectdetailpage',
            name='header_button_text',
        ),
        migrations.RemoveField(
            model_name='projectdetailpage',
            name='header_description',
        ),
        migrations.RemoveField(
            model_name='projectdetailpage',
            name='overlay_body',
        ),
        migrations.RemoveField(
            model_name='projectdetailpage',
            name='overlay_button_page',
        ),
        migrations.RemoveField(
            model_name='projectdetailpage',
            name='overlay_button_text',
        ),
        migrations.RemoveField(
            model_name='projectdetailpage',
            name='overlay_image',
        ),
        migrations.RemoveField(
            model_name='projectdetailpage',
            name='overlay_title',
        ),
        migrations.AddField(
            model_name='projectdetailpage',
            name='content',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True, verbose_name='Paragraphs and pictures'),
        ),
        migrations.AddField(
            model_name='projectdetailpage',
            name='description',
            field=wagtail.fields.RichTextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='projectdetailpage',
            name='project',
            field=models.ForeignKey(blank=True, help_text='If set, some project details from the projects section in the partners app will be included in the website.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_pages', to='partners.project', verbose_name='Related project in the Partners app'),
        ),
        migrations.AlterField(
            model_name='projectdetailpage',
            name='header_image',
            field=models.ForeignKey(help_text="Aquesta imatge està pensada per ser decorativa i crear acompanyar el contingut. Segons la resolució i el dispositiu de l'usuari, la mida i proporció variarà, i per tant es retallaran parts de la imatge. La proporció recomanada és de 2x1, amb una mida mínima de 2.000x1.000px.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
    ]
