# Generated by Django 5.1.3 on 2024-11-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_remove_projectdetailpage_display_header_highlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetailpage',
            name='status',
            field=models.CharField(choices=[('PS', 'Project in study phase'), ('AP', 'Active Project'), ('OP', 'Future projects or other projects')], default='', max_length=2, verbose_name='Status'),
        ),
    ]
