# Generated by Django 5.1.3 on 2024-11-14 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_alter_project_created_at'),
        ('web', '0020_projectdetailpage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetailpage',
            name='project',
            field=models.ForeignKey(blank=True, help_text='If set, some project details from the projects section in the partners app will be included in the website. To create or edit those projects, go to the <a href="/admin/partners/project/">admin panel</a>.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_pages', to='partners.project', verbose_name='Related project in the Partners app'),
        ),
    ]
