# Generated by Django 5.1.3 on 2024-11-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_projectdetailpage_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetailpage',
            old_name='project',
            new_name='partners_project',
        ),
    ]
