# Generated by Django 5.1.3 on 2024-11-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_rename_project_projectdetailpage_partners_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetailpage',
            name='show_in_home',
            field=models.BooleanField(default=False, help_text="If selected, this project will appear on the home page in the 'What do we offer?' block.", verbose_name='Show in the home page'),
        ),
    ]
