# Generated by Django 5.1.3 on 2024-11-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_projectdetailpage_show_in_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='projects_title',
            field=models.CharField(default='What does Castellet Sostenible offer?', max_length=80, verbose_name='Title'),
        ),
    ]
