# Generated by Django 5.1.3 on 2024-11-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_homepage_projects_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='news_title',
            field=models.CharField(default='Last news', max_length=80, verbose_name='Title'),
        ),
    ]
