# Generated by Django 5.1.3 on 2024-11-22 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('web', '0025_homepage_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='display_header_highlight',
            field=models.BooleanField(default=True, help_text='Per mostrar el missatge superposat a la capçalera cal marcar aquesta opció i omplir les dades del bloc Missatge sobre la capçalera.', verbose_name='Display header highlighted overlay'),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='header_image',
            field=models.ForeignKey(help_text='This image is intended to be decorative and creative to accompany the content. Depending on the resolution and device of the user, the size and proportion will vary, and therefore parts of the image will be cropped. The recommended proportion is 2x1, with a minimum size of 2,000x1,000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='display_header_highlight',
            field=models.BooleanField(default=True, help_text='Per mostrar el missatge superposat a la capçalera cal marcar aquesta opció i omplir les dades del bloc Missatge sobre la capçalera.', verbose_name='Display header highlighted overlay'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_image',
            field=models.ForeignKey(help_text='This image is intended to be decorative and creative to accompany the content. Depending on the resolution and device of the user, the size and proportion will vary, and therefore parts of the image will be cropped. The recommended proportion is 2x1, with a minimum size of 2,000x1,000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='newsdetailpage',
            name='header_image',
            field=models.ForeignKey(help_text='This image is intended to be decorative and creative to accompany the content. Depending on the resolution and device of the user, the size and proportion will vary, and therefore parts of the image will be cropped. The recommended proportion is 2x1, with a minimum size of 2,000x1,000px.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='projectdetailpage',
            name='header_image',
            field=models.ForeignKey(help_text='This image is intended to be decorative and creative to accompany the content. Depending on the resolution and device of the user, the size and proportion will vary, and therefore parts of the image will be cropped. The recommended proportion is 2x1, with a minimum size of 2,000x1,000px.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='projectlistpage',
            name='display_header_highlight',
            field=models.BooleanField(default=True, help_text='Per mostrar el missatge superposat a la capçalera cal marcar aquesta opció i omplir les dades del bloc Missatge sobre la capçalera.', verbose_name='Display header highlighted overlay'),
        ),
        migrations.AlterField(
            model_name='projectlistpage',
            name='header_image',
            field=models.ForeignKey(help_text='This image is intended to be decorative and creative to accompany the content. Depending on the resolution and device of the user, the size and proportion will vary, and therefore parts of the image will be cropped. The recommended proportion is 2x1, with a minimum size of 2,000x1,000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
    ]
