# Generated by Django 5.1.3 on 2024-11-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_footerlogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlogo',
            name='title',
        ),
    ]
