# Generated by Django 5.1.3 on 2024-11-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_remove_footerlogo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='menu_label',
            field=models.CharField(blank=True, default='', help_text='If not set, the menu title will be the page title.', max_length=15, verbose_name='Menu title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customizationsettings',
            name='join_us_title',
            field=models.CharField(default='Join Castellet Sostenible', max_length=240, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='menu_label',
            field=models.CharField(blank=True, default='', help_text='If not set, the menu title will be the page title.', max_length=15, verbose_name='Menu title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='menu_label',
            field=models.CharField(blank=True, default='', help_text='If not set, the menu title will be the page title.', max_length=15, verbose_name='Menu title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newslistpage',
            name='menu_label',
            field=models.CharField(blank=True, default='', help_text='If not set, the menu title will be the page title.', max_length=15, verbose_name='Menu title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectlistpage',
            name='menu_label',
            field=models.CharField(blank=True, default='', help_text='If not set, the menu title will be the page title.', max_length=15, verbose_name='Menu title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmediaiconssettings',
            name='facebook',
            field=models.URLField(blank=True, default='', help_text='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='socialmediaiconssettings',
            name='instagram',
            field=models.URLField(blank=True, default='https://www.instagram.com/castelletsostenible/', help_text='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='socialmediaiconssettings',
            name='x',
            field=models.URLField(blank=True, default='', help_text='X URL'),
        ),
        migrations.AlterField(
            model_name='socialmediaiconssettings',
            name='youtube',
            field=models.URLField(blank=True, default='', help_text='Youtube URL'),
        ),
    ]
