version: "3.5"

networks:
  castellet-network:
    name: castellet-network

services:
  castellet-app:
    restart: on-failure
    container_name: castellet-app
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./.env
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 --reload --threads=10
    ports:
      - "1501:8000"
    volumes:
      - ../src:/srv
    depends_on:
      - castellet-db
    networks:
      - castellet-network

  castellet-db:
    container_name: castellet-db
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ../dumps:/dumps
    networks:
      - castellet-network


  castellet-selenium:
    container_name: castellet-selenium
    image: selenium/standalone-chrome:4.16.0
    networks:
      - castellet-network
